### ISSUE TITLE
[Bug] With the manual world optimization chunk deletion, structures at chunk edges will have blocks cut off

### ISSUE THREAD

**Issue by shal0l** [TheCSMods/mc-no-unused-chunks#13]
Like this:
![javaw_lqKvK4glYM](https://user-images.githubusercontent.com/67803583/226076213-736e43e5-6942-40a5-8161-78fdab18bbdd.png)

It could (handily?) be mitigated if there was logic to maintain the save flag for the neighboring chunks in a radius, of edited/player visited chunks.

Regardless of feasibility, the mod is still great as is. Thank you!

**Comment by TheCSDev** [comment]
Interesting bug, thanks for reporting it, and also thanks for suggesting how it could be fixed.

Tho, I am having a bit of a hard time trying to figure out what exactly happened here and what caused it. Usually when a chunk is discarded, it is supposed to be re-generated in the same way it was generated prior to being discarded, so having a cut-off tree appear does confuse me a bit.

Also, I was thinking about a similar thing and worrying it might be an issue when it comes larger strustures like fortresses. Specifically, what if the player puts the "save flag" on one half of a structure, and then discards the other half with the mod. But even in that case, the other half should just re-generate with no issues as far as I know.

So how that tree managed to get cut-off instead of re-generated properly does confuse me. If it is because the tree structure refused to generate its other half in a player-modified chunk, then the leaves in that player-modified chunk should have remained from the previous generation unless they got removed manually?

I guess will try to figure out what the issue could be. In the meantime, you could also let me know how you think this took place and what you did to replicate the issue.
Thanks again and have a great day!

**Comment by shal0l** [comment]
Bad report, it's not affecting structures. That was a poor assumption based on the trees. Just trees.
While this was my original assumption:
```
I'd guess it would be due to the tree (analogy to a sapling) belonging to the player edited chunk, and while the structure leaves/blocks may happen to go outside the chunk, the root tree place/coordinate is still at the flagged chunk. 
Therefore, it won't re-generate the leaves because the origin tree of these leaves hasn't been deleted and thus won't generate itself and thus the leaves for the deleted chunk.
```
After just trying it on a new 1.19.2 world, no mods, latest forge, it seems to be "randomly" picking chunks and doing something with the tree blocks generation, even if the nearby chunks were left untouched, which is mildly concerning. So maybe forget my fix suggestion because it appears to be a whole other issue now.. 
*Doesn't happen with the mods auto chunk unflagging, only manual blast?

https://user-images.githubusercontent.com/67803583/226160947-2b73f10e-2db8-4f4a-bf31-5474174e0411.mp4

**Comment by TheCSDev** [comment]
# I will now pin this issue in case anyone else encounters it
## If anyone's interested in why it happens, [here's why (please click here)](https://youtu.be/4O0_-1NaWnY?t=681).  
Unfortunately this bug is **un-resolvable** from my end.  
  
Basically, when Minecraft generates trees at chunk edges next to un-loaded and non-existing chunks, it stores the coordinates and information about those "unfinished' trees on the physical hard drive. The next time you walk close enough to the non-existing chunks next to those trees, the game will retrieve the data about the "unfinished" trees from the hard drive, after which it will "finish" them whenever possible.

The problem is, when removing already previously generated chunks, the trees will go back to being "unfinished", but this time, since they were already generated before, nothing will keep track of them again, resulting in them remaining "unfinished" and "cut-off" after removing unused chunks that are next to them.

This unfortunately, is not possible to fix.
