### ISSUE TITLE
1.20.1 please

### ISSUE THREAD

**Issue by ProletariatRR** [TheCSMods/mc-no-unused-chunks#15]
This is a good mod, I'm running out of disk space on my 1.20.1 server, I sincerely request you to update this project to 1.20.1. have a good day!

（by Google Translate

**Comment by MCRusher** [comment]
In the meantime there's a php library called [thanos](https://github.com/aternosorg/thanos) that can be used to delete unused chunks in a world that I've had success with (it pruned a full GB even on my small 2 person server).

You'll have to install php and composer though to use it.

**Comment by NerdTo** [comment]
> In the meantime there's a php library called [thanos](https://github.com/aternosorg/thanos) that can be used to delete unused chunks in a world that I've had success with (it pruned a full GB even on my small 2 person server).
> 
> You'll have to install php and composer though to use it.
> 
> It's not automatic so you have to run the script yourself, but it does work.

Please update the mod, I need it too

**Comment by NerdTo** [comment]
I changed the OS and it left me with 2+- GB of free space

**Comment by NerdTo** [comment]
This can't go on much longer, please, please update the mod.

**Comment by NerdTo** [comment]
![image](https://github.com/TheCSMods/mc-no-unused-chunks/assets/116191734/a6dfcaa8-f897-4459-852d-951e4912c141)

**Comment by TheCSDev** [comment]
Hello everyone.
I unfortunately don't think I can focus on the development of this mod as much as I used to before, as there are many other things I have to focus on as well.

However, I did make an alternative tool.
@MCRusher mentioned [Thanos](https://github.com/aternosorg/thanos). I did hear of this tool before, and it's an awesome one too. However, getting it to work can be complicated for most people. I mean.. installing php, installing script dependencies, handling php environment variables... Too complicated.

I used this [Thanos](https://github.com/aternosorg/thanos) library to make a simple PowerShell script that removes unused chunks from Minecraft worlds. It comes bundled with php and everything the script depends on, so no need to do unnecessary complicated installations yourself. Everything's bundled in there.

All you have to do is, download the `run.ps1` script, right click it, select "Run with PowerShell", and that's it.  
This script should be a lot easier to work with for most people. [Here's the download](https://github.com/TheCSMods/mc-no-unused-chunks/releases/tag/ts-v0.0.1%2B1.20.1). The download is here on GitHub.

**Comment by NerdTo** [comment]
> Hello everyone. I unfortunately don't think I can focus on the development of this mod as much as I used to before, as there are many other things I have to focus on as well.
> 
> However, I did make an alternative tool. @MCRusher mentioned [Thanos](https://github.com/aternosorg/thanos). I did hear of this tool before, and it's an awesome one too. However, getting it to work can be complicated for most people. I mean.. installing php, installing script dependencies, handling php environment variables... Too complicated.
> 
> So that's why I used this [Thanos](https://github.com/aternosorg/thanos) library to make a simple PowerShell script that removes unused chunks from Minecraft worlds. It comes bundled with php and everything the script depends on, so no need to do unnecessary complicated installations yourself. Everything's bundled in there.
> 
> All you have to do is, download the `run.ps1` script, right click it, select "Run with PowerShell", and that's it. This script should be a lot easier to work with for most people. [The download is here on GitHub. (click here)](https://github.com/TheCSMods/mc-no-unused-chunks/releases/tag/ts-v0.0.1%2B1.20.1).

How do I do it on Oracle Linux?

**Comment by NerdTo** [comment]
hmm

**Comment by TheCSDev** [comment]
Done. [I uploaded a Linux version](https://github.com/TheCSMods/mc-no-unused-chunks/releases/tag/ts-v0.0.1%2B1.20.1). Hopefully this one works out for you. Keep in mind you will have to install `php`, but don't worry, there are detailed instructions on how to do it. It's literally just one command.

**Comment by NerdTo** [comment]
Oh, sorry bro for wasting your time, but I found a way. I used the trim command in the chunky mod...

**Comment by NerdTo** [comment]
sorry

**Comment by TheCSDev** [comment]
That's alright. Someone else using Linux may eventually end up here anyways, so it'll help them as well.

**Comment by Cyclopropinon** [comment]
> That's alright. Someone else using Linux may eventually end up here anyways, so it'll help them as well.

yeah it actually helped me, since im using linux :)

**Comment by SulpherStaer** [comment]
Would financial compensation give sufficient incentive to focus on this project? (Dependant on amount obviously)

If so, I'd like to talk in a less public area with you to discuss details. If not, then sad me :-/ This mod is awesome.

**Comment by TheCSDev** [comment]
> Would financial compensation give sufficient incentive to focus on this project? (Dependant on amount obviously)
> 
> If so, I'd like to talk in a less public area with you to discuss details. If not, then sad me :-/ This mod is awesome.

Seeing there's a demand for an update for this mod eventually ended up being an incentive, so I have decided to work on a `1.20.x` port. I will be focusing on `Fabric` loader for now, as that is the loader I mainly mod on (dealing with both at once is too hard).

I think I already have a working prototype, but first I will test it thoroughly before doing anything with it, as peoples worlds are at stake when it comes to this mod.

Another thing to point out is, I won't port the feature that automatically discards chunks "on-the-go" as you play the game, as that seemed to repel many people from using the mod in the first place. The feature was a common criticism of this mod, which maskes sense, as it technically made this mod a "deoptimization" mod. Sacrificing performance for storage isn't seen as beneficial. I will however, port the feature that removes existing unused chunks from the world optimization screen.

As for the "financial compensation" part.. while the idea sounds nice in theory, in practice, I'd say it's complicated. First, I personally don't like asking people for money or even taking it, unless they really wanna donate it on their own accord (without my input or any expectations). I've been modding for quite a while, and if there's one thing I learned from that, it's that literally at any moment anything can go wrong, in some cases even killing the entire project. Problem with that is, what if someone donates or gives money expecting something, and then that something turns out to be either impossible or too difficult for me to pull off to the point where I don't even know how to do it. While this mod doesn't seem one of those cases, you never know what can happen the very next moment you decide to write the next line of code. You could encounter an error, then check Minecraft's source code, only to realize Mojang made a "game-breaking" (aka mod-breaking) change, and hen be forced to scrap the entire project mid-way-thru or find a too complicated workaround.  
- In this mod's case, the "mod-breaking" thing would be Mojang either removing or changing the behavior of the `InhabitedTime` property that chunks have, which this mod depends on in order to tell if a chunk is unused or not, whereas Mojang uses it for "local difficulty" purposes.

Anyways, I'll go back to testing the prototype. Hopefully it works as expected.
