### ISSUE TITLE
Please add 1.20.1 Forge support or

### ISSUE THREAD

**Issue by SkyKingPX** [TheCSMods/mc-no-unused-chunks#17]
If you can not, then please tell me, if I can make a Fabric server, remove unused Chunks and if I then could go back to Forge again.
Thanks

**Comment by TheCSDev** [comment]
Hello.

Sorry in advance, but I currently have no plans for writing a Forge port for this mod, as not only do I mainly write mods on Fabric, but I am currently focused on two other mods of mine that need an update asap (updates that'll take a long time to be done).

By the way, the 1.20.1 version of this mod is client-side-only, so no need to try and install it onto any servers or anything, as the automatic/live chunk discarding feature wasn't ported to 1.20.1 due to performance concerns (for obvious reasons, people prioritize performance over storage).

In the meantime, you can also give [Thanos Shell](https://github.com/TheCSMods/mc-no-unused-chunks/releases/tag/ts-v0.0.1%2B1.20.1) (the tool I wrote that is based on [Thanos](https://github.com/aternosorg/thanos)) a try. It doesn't even require Minecraft at all, completely independent from the game (so no need to worry about "Fabric or Forge"). If you decide to use that, you can directly optimize your world files without booting up the game (just make sure the game or the server is powered off at the moment you use the tool).

Again, sorry about not having my mods for Forge most of the time (except in some super rare cases ig). And have a great day!
